import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import { Roboto as FontSans } from "next/font/google";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

import { cn, getUserId } from "@/lib/utils";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import Script from "next/script";
import ClientLayout from "@/components/layout/ClientLayout";
import { UserProvider } from "./providers/UserContext";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="text-base">
      <body
        className={cn(
          "h-svh w-full  bg-background font-sans antialiased ",
          fontSans.variable
        )}
      >
        <div className="flex flex-col justify-between fixed w-full h-full top-0 bottom-0 left-0 right-0 text-main-black">
          <Script
            strategy="afterInteractive"
            src="https://telegram.org/js/telegram-web-app.js"
          />
          {/* <Header /> */}
          <ClientLayout>client</ClientLayout>
          <UserProvider>
            <>
              {children}
              <Footer />
            </>
          </UserProvider>
        </div>
      </body>
    </html>
  );
}
